-- Librairie El Qods - Supabase setup
-- Copy this file into Supabase SQL Editor, then run it once for the new project.

create table if not exists public.school_lists (
    id bigint generated by default as identity primary key,
    school_name text not null,
    school_logo_url text,
    level text not null,
    items jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    client_name text not null,
    client_phone text not null,
    client_email text,
    items jsonb not null default '[]'::jsonb,
    status text not null default 'new',
    reservation_deadline timestamptz,
    total_amount numeric not null default 0,
    payment_method text not null default 'cash_pickup',
    created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
    key text primary key,
    value text not null
);

insert into public.site_settings (key, value) values
    ('rentree_enabled', 'true'),
    ('rentree_title', 'Rentrée scolaire'),
    ('contact_address', 'Adresse de la boutique à compléter'),
    ('contact_email', 'contact@example.com'),
    ('contact_phone', '0000000000'),
    ('contact_whatsapp', '212600000000'),
    ('contact_facebook', ''),
    ('contact_instagram', ''),
    ('contact_linkedin', '')
on conflict (key) do nothing;

alter table public.school_lists enable row level security;
alter table public.orders enable row level security;
alter table public.site_settings enable row level security;

drop policy if exists "Public can read school lists" on public.school_lists;
create policy "Public can read school lists"
on public.school_lists for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated admins can manage school lists" on public.school_lists;
create policy "Authenticated admins can manage school lists"
on public.school_lists for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders"
on public.orders for insert
to anon, authenticated
with check (true);

drop policy if exists "Authenticated admins can manage orders" on public.orders;
create policy "Authenticated admins can manage orders"
on public.orders for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings"
on public.site_settings for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated admins can manage site settings" on public.site_settings;
create policy "Authenticated admins can manage site settings"
on public.site_settings for all
to authenticated
using (true)
with check (true);

-- Optional storage setup for photo uploads:
-- 1. In Supabase Dashboard > Storage, create a public bucket named: lists
-- 2. If you enable storage RLS manually, allow public upload/read only if that matches your shop workflow.


-- Consignes libres saisies par le client pour une commande
alter table public.orders
add column if not exists order_instructions text;

comment on column public.orders.order_instructions is
'Consignes facultatives laissées par le client lors de la commande';


-- Logo facultatif de l'école (fichier stocké sur Google Drive ou autre URL publique)
alter table public.school_lists
add column if not exists school_logo_url text;

comment on column public.school_lists.school_logo_url is
'URL facultative du logo de l école. Si vide, le site affiche l initiale de l établissement.';

insert into public.site_settings (key,value) values ('delivery_enabled','false') on conflict (key) do nothing;
